# Server
server.port=8080
spring.application.name=skill-tracker-backend

# MongoDB - Docker avec authentification
spring.data.mongodb.uri=mongodb://mongodb:27017/skill_tracker_db

# JWT Configuration
jwt.secret=3f8b2c1a9d7e4f6a2b8c5d3e7f1a4b9c2d6e8f3a7b1c5d9e2f4a6b8c1d3e5f7
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost

# Logs
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.tn.iteam=DEBUG